#!/usr/bin/env python3
"""Transform a cargo-modules dependency graph into a layered architecture diagram.

Input  : raw DOT from `cargo modules dependencies --lib ...` (module nodes plus
         "owns" tree edges and "uses" dependency edges).
Output : a top-down, cluster-per-layer DOT where each module is bucketed into one
         of the project's architectural layers and only *dependency* ("uses")
         edges are drawn.

Why a transform instead of using the raw graph: cargo-modules marks `uses` edges
`constraint=false` (so the file tree, not dependencies, drives its layout) and it
has no concept of "layers". We drop the redundant `owns` edges (the clusters
already convey containment), flip cross-layer `uses` edges to `constraint=true`
so dependencies stack the layers vertically, and box each layer.

`app` and `main` live in the *binary* crate, which cargo-modules analyzes as a
separate crate that sees the library as one opaque extern -- so their edges into
individual lib modules are not machine-derivable. They are added here as a
labeled "binary shell" top layer from source inspection (see SYNTH_* below).

Usage: layer_dot.py <raw-modules.dot> <out-architecture.dot>
"""
import re
import sys

CRATE = "git_branch_manager"

# layer index -> (label, node fill color, cluster background color)
# Displayed top (highest index) to bottom (0); dependencies point downward.
LAYERS = {
    0: ("L0 · Domain types", "#8ec7ff", "#eef5ff"),
    1: ("L1 · Config & presentation primitives", "#9ad99a", "#eefaee"),
    2: ("L2 · Git backend", "#ffc680", "#fff4e6"),
    3: ("L3 · View models", "#d8a8f0", "#f7eefc"),
    4: ("L4 · UI widgets", "#ff9f9f", "#ffeeee"),
    5: ("L5 · App state machine (binary)", "#ffe066", "#fffae6"),
    6: ("L6 · Entrypoint (binary)", "#c8c8c8", "#f2f2f2"),
}

# Representative node per layer, used to anchor invisible ordering edges that
# guarantee the layers stack top-to-bottom even if some layer lacks a cross edge.
ANCHOR = {
    0: f"{CRATE}::types",
    1: f"{CRATE}::config",
    2: f"{CRATE}::git",
    3: f"{CRATE}::view",
    4: f"{CRATE}::ui",
    5: "app",
    6: "main",
}

# Binary-shell nodes absent from the lib graph (see module docstring).
SYNTH_NODES = {"app": 5, "main": 6}
# Representative binary-shell dependencies, from app.rs / main.rs imports.
SYNTH_EDGES = [
    ("main", "app"),
    ("main", f"{CRATE}::cli"),
    ("app", f"{CRATE}::ui"),
    ("app", f"{CRATE}::view"),
    ("app", f"{CRATE}::git"),
    ("app", f"{CRATE}::config"),
    ("app", f"{CRATE}::types"),
]


def classify(node_id):
    """Map a module path to a layer index, or None to drop it (e.g. crate root)."""
    short = node_id.replace(f"{CRATE}::", "")
    if short == "types":
        return 0
    if short in ("config", "theme", "symbols", "cli"):
        return 1
    if short == "git" or short.startswith("git::"):
        return 2
    if short == "view" or short.startswith("view::"):
        return 3
    if short == "ui" or short.startswith("ui::"):
        return 4
    if short == "app":
        return 5
    if short == "main":
        return 6
    return None  # bare crate root (lib.rs re-exports) -> dropped as noise


def short_label(node_id):
    return SYNTH_LABEL.get(node_id) or node_id.replace(f"{CRATE}::", "")


SYNTH_LABEL = {"app": "app", "main": "main"}

NODE_RE = re.compile(r'^\s*"([^"]+)"\s*\[label=')
USES_RE = re.compile(r'^\s*"([^"]+)"\s*->\s*"([^"]+)"\s*\[label="uses"')


def main():
    raw_path, out_path = sys.argv[1], sys.argv[2]
    with open(raw_path, encoding="utf-8") as fh:
        lines = fh.readlines()

    node_layer = {}
    for line in lines:
        if "->" in line:
            continue
        m = NODE_RE.match(line)
        if not m:
            continue
        nid = m.group(1)
        layer = classify(nid)
        if layer is not None:
            node_layer[nid] = layer

    # Synthetic binary-shell nodes.
    for nid, layer in SYNTH_NODES.items():
        node_layer[nid] = layer

    # Collect "uses" edges between nodes we kept (dropping the crate root).
    uses = []
    seen = set()
    for line in lines:
        if "->" not in line:
            continue
        m = USES_RE.match(line)
        if not m:
            continue
        src, dst = m.group(1), m.group(2)
        if src in node_layer and dst in node_layer and (src, dst) not in seen:
            seen.add((src, dst))
            uses.append((src, dst))

    by_layer = {i: [] for i in LAYERS}
    for nid, layer in sorted(node_layer.items()):
        by_layer[layer].append(nid)

    out = []
    out.append("digraph architecture {")
    out.append('    // GENERATED by scripts/gen-arch-diagram.sh -- do not edit by hand.')
    out.append("    graph [")
    out.append('        label="git-branch-manager — layered architecture",')
    out.append("        labelloc=t, fontname=Helvetica, fontsize=28,")
    out.append("        layout=dot, rankdir=TB, newrank=true,")
    out.append("        splines=polyline, concentrate=true,")
    out.append("        ranksep=1.1, nodesep=0.3, pad=0.4,")
    out.append("    ];")
    out.append('    node [shape=box, style="rounded,filled", fontname=monospace,')
    out.append('          fontsize=11, margin="0.12,0.06"];')
    out.append('    edge [fontname=monospace, fontsize=9];')
    out.append("")

    # Clusters, highest layer first so the file reads top-to-bottom.
    for layer in sorted(LAYERS, reverse=True):
        label, fill, bg = LAYERS[layer]
        out.append(f"    subgraph cluster_L{layer} {{")
        out.append(f'        label="{label}"; style=filled; color="#aaaaaa";')
        out.append(f'        fillcolor="{bg}"; fontname=Helvetica; fontsize=14;')
        out.append(f'        node [fillcolor="{fill}"];')
        for nid in by_layer[layer]:
            out.append(f'        "{nid}" [label="{short_label(nid)}"];')
        out.append("    }")
        out.append("")

    # Pin every module in a layer to the same rank so each layer is one
    # horizontal band. Safe because intra-layer "uses" edges are emitted with
    # constraint=false below, and newrank=true lets rank=same span clusters.
    out.append("    // force one horizontal band per layer")
    for layer in sorted(LAYERS, reverse=True):
        members = by_layer[layer]
        if len(members) > 1:
            ids = " ".join(f'"{nid}";' for nid in members)
            out.append(f"    {{ rank=same; {ids} }}")
    out.append("")

    # Dependency edges. Intra-layer edges stay constraint=false (drawn flat);
    # cross-layer edges drive the vertical ranking (constraint=true).
    out.append("    // dependency (uses) edges")
    for src, dst in uses:
        cross = node_layer[src] != node_layer[dst]
        constraint = "true" if cross else "false"
        out.append(
            f'    "{src}" -> "{dst}" '
            f'[color="#7f7f7f", style=dashed, constraint={constraint}];'
        )
    out.append("")

    # Binary-shell edges (added from source; see module docstring).
    out.append("    // binary-shell edges (app/main -> library), from source")
    for src, dst in SYNTH_EDGES:
        if src in node_layer and dst in node_layer:
            out.append(f'    "{src}" -> "{dst}" [color="#444444", penwidth=1.3];')
    out.append("")

    # Invisible anchor chain to guarantee layer ordering top-to-bottom.
    out.append("    // invisible ordering anchors")
    present = [i for i in sorted(LAYERS, reverse=True) if ANCHOR[i] in node_layer]
    for hi, lo in zip(present, present[1:]):
        out.append(
            f'    "{ANCHOR[hi]}" -> "{ANCHOR[lo]}" '
            f"[style=invis, weight=20, constraint=true];"
        )

    out.append("}")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")

    n_nodes = len(node_layer)
    print(
        f"layered: {n_nodes} nodes, {len(uses)} dependency edges, "
        f"{len(SYNTH_EDGES)} binary-shell edges -> {out_path}"
    )


if __name__ == "__main__":
    main()
